// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messaggi_partita.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ScoponeScientifico {
  public static partial class go_backend
  {
    static readonly string __ServiceName = "Scopone_Scientifico.go_backend";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ScoponeScientifico.game_settings> __Marshaller_Scopone_Scientifico_game_settings = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ScoponeScientifico.game_settings.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ScoponeScientifico.initial_state> __Marshaller_Scopone_Scientifico_initial_state = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ScoponeScientifico.initial_state.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ScoponeScientifico.card> __Marshaller_Scopone_Scientifico_card = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ScoponeScientifico.card.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ScoponeScientifico.turn_update> __Marshaller_Scopone_Scientifico_turn_update = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ScoponeScientifico.turn_update.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ScoponeScientifico.observe_request> __Marshaller_Scopone_Scientifico_observe_request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ScoponeScientifico.observe_request.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ScoponeScientifico.score_update> __Marshaller_Scopone_Scientifico_score_update = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ScoponeScientifico.score_update.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ScoponeScientifico.game_settings, global::ScoponeScientifico.initial_state> __Method_start_game = new grpc::Method<global::ScoponeScientifico.game_settings, global::ScoponeScientifico.initial_state>(
        grpc::MethodType.Unary,
        __ServiceName,
        "start_game",
        __Marshaller_Scopone_Scientifico_game_settings,
        __Marshaller_Scopone_Scientifico_initial_state);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ScoponeScientifico.card, global::ScoponeScientifico.turn_update> __Method_play_card = new grpc::Method<global::ScoponeScientifico.card, global::ScoponeScientifico.turn_update>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "play_card",
        __Marshaller_Scopone_Scientifico_card,
        __Marshaller_Scopone_Scientifico_turn_update);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ScoponeScientifico.observe_request, global::ScoponeScientifico.turn_update> __Method_observe_turn = new grpc::Method<global::ScoponeScientifico.observe_request, global::ScoponeScientifico.turn_update>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "observe_turn",
        __Marshaller_Scopone_Scientifico_observe_request,
        __Marshaller_Scopone_Scientifico_turn_update);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ScoponeScientifico.observe_request, global::ScoponeScientifico.score_update> __Method_calcola_punteggio = new grpc::Method<global::ScoponeScientifico.observe_request, global::ScoponeScientifico.score_update>(
        grpc::MethodType.Unary,
        __ServiceName,
        "calcola_punteggio",
        __Marshaller_Scopone_Scientifico_observe_request,
        __Marshaller_Scopone_Scientifico_score_update);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ScoponeScientifico.MessaggiPartitaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of go_backend</summary>
    [grpc::BindServiceMethod(typeof(go_backend), "BindService")]
    public abstract partial class go_backendBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ScoponeScientifico.initial_state> start_game(global::ScoponeScientifico.game_settings request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task play_card(global::ScoponeScientifico.card request, grpc::IServerStreamWriter<global::ScoponeScientifico.turn_update> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task observe_turn(global::ScoponeScientifico.observe_request request, grpc::IServerStreamWriter<global::ScoponeScientifico.turn_update> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ScoponeScientifico.score_update> calcola_punteggio(global::ScoponeScientifico.observe_request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for go_backend</summary>
    public partial class go_backendClient : grpc::ClientBase<go_backendClient>
    {
      /// <summary>Creates a new client for go_backend</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public go_backendClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for go_backend that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public go_backendClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected go_backendClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected go_backendClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScoponeScientifico.initial_state start_game(global::ScoponeScientifico.game_settings request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return start_game(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScoponeScientifico.initial_state start_game(global::ScoponeScientifico.game_settings request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_start_game, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScoponeScientifico.initial_state> start_gameAsync(global::ScoponeScientifico.game_settings request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return start_gameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScoponeScientifico.initial_state> start_gameAsync(global::ScoponeScientifico.game_settings request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_start_game, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::ScoponeScientifico.turn_update> play_card(global::ScoponeScientifico.card request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return play_card(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::ScoponeScientifico.turn_update> play_card(global::ScoponeScientifico.card request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_play_card, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::ScoponeScientifico.turn_update> observe_turn(global::ScoponeScientifico.observe_request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return observe_turn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::ScoponeScientifico.turn_update> observe_turn(global::ScoponeScientifico.observe_request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_observe_turn, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScoponeScientifico.score_update calcola_punteggio(global::ScoponeScientifico.observe_request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return calcola_punteggio(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScoponeScientifico.score_update calcola_punteggio(global::ScoponeScientifico.observe_request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_calcola_punteggio, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScoponeScientifico.score_update> calcola_punteggioAsync(global::ScoponeScientifico.observe_request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return calcola_punteggioAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScoponeScientifico.score_update> calcola_punteggioAsync(global::ScoponeScientifico.observe_request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_calcola_punteggio, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override go_backendClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new go_backendClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(go_backendBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_start_game, serviceImpl.start_game)
          .AddMethod(__Method_play_card, serviceImpl.play_card)
          .AddMethod(__Method_observe_turn, serviceImpl.observe_turn)
          .AddMethod(__Method_calcola_punteggio, serviceImpl.calcola_punteggio).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, go_backendBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_start_game, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ScoponeScientifico.game_settings, global::ScoponeScientifico.initial_state>(serviceImpl.start_game));
      serviceBinder.AddMethod(__Method_play_card, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::ScoponeScientifico.card, global::ScoponeScientifico.turn_update>(serviceImpl.play_card));
      serviceBinder.AddMethod(__Method_observe_turn, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::ScoponeScientifico.observe_request, global::ScoponeScientifico.turn_update>(serviceImpl.observe_turn));
      serviceBinder.AddMethod(__Method_calcola_punteggio, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ScoponeScientifico.observe_request, global::ScoponeScientifico.score_update>(serviceImpl.calcola_punteggio));
    }

  }
}
#endregion
