// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messaggi_partita.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ScoponeScientifico {

  /// <summary>Holder for reflection information generated from messaggi_partita.proto</summary>
  public static partial class MessaggiPartitaReflection {

    #region Descriptor
    /// <summary>File descriptor for messaggi_partita.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessaggiPartitaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZtZXNzYWdnaV9wYXJ0aXRhLnByb3RvEhNTY29wb25lX1NjaWVudGlmaWNv",
            "IiIKD29ic2VydmVfcmVxdWVzdBIPCgdnYW1lX0lEGAEgASgFIjYKDWdhbWVf",
            "c2V0dGluZ3MSEQoJdXNlcl9uYW1lGAEgASgJEhIKCm1heF9wb2ludHMYAiAB",
            "KAUiWAoEY2FyZBInCgRzdWl0GAIgASgOMhkuU2NvcG9uZV9TY2llbnRpZmlj",
            "by5TdWl0EicKBHJhbmsYAyABKA4yGS5TY29wb25lX1NjaWVudGlmaWNvLlJh",
            "bmsifgoLUGxheVJlcXVlc3QSDwoHZ2FtZV9JRBgBIAEoBRIuCgtwbGF5ZWRf",
            "Y2FyZBgCIAEoCzIZLlNjb3BvbmVfU2NpZW50aWZpY28uY2FyZBIuCgt0YXJn",
            "ZXRfY2FyZBgDIAMoCzIZLlNjb3BvbmVfU2NpZW50aWZpY28uY2FyZCI2CgpD",
            "b2JpbmF0aW9uEigKBWNhcmRzGAEgAygLMhkuU2NvcG9uZV9TY2llbnRpZmlj",
            "by5jYXJkIrEBCg1pbml0aWFsX3N0YXRlEg8KB2dhbWVfSUQYASABKAUSLAoJ",
            "dXNlcl9oYW5kGAIgAygLMhkuU2NvcG9uZV9TY2llbnRpZmljby5jYXJkEi0K",
            "CWRlYWxlcl9JRBgDIAEoDjIaLlNjb3BvbmVfU2NpZW50aWZpY28uQWN0b3IS",
            "MgoOY3VycmVudF9wbGF5ZXIYBCABKA4yGi5TY29wb25lX1NjaWVudGlmaWNv",
            "LkFjdG9yIscCCgt0dXJuX3VwZGF0ZRIpCgVhY3RvchgBIAEoDjIaLlNjb3Bv",
            "bmVfU2NpZW50aWZpY28uQWN0b3ISLgoLcGxheWVkX2NhcmQYAiABKAsyGS5T",
            "Y29wb25lX1NjaWVudGlmaWNvLmNhcmQSLgoLY2FydGVfcHJlc2UYAyADKAsy",
            "GS5TY29wb25lX1NjaWVudGlmaWNvLmNhcmQSDQoFc2NvcGEYBCABKAgSFQoN",
            "aXNfbWF0Y2hfb3ZlchgFIAEoCBIyCg5uZXh0X3BsYXllcl9JRBgGIAEoDjIa",
            "LlNjb3BvbmVfU2NpZW50aWZpY28uQWN0b3ISIgoaY29uZmxpY3RfcmVzb2x1",
            "dGlvbl9uZWVkZWQYByABKAgSLwoGb3B0aW9uGAggAygLMh8uU2NvcG9uZV9T",
            "Y2llbnRpZmljby5Db2JpbmF0aW9uIskBCgxzY29yZV91cGRhdGUSDwoHZ2Ft",
            "ZV9JRBgBIAEoBRIXCg91c2VyX3NxdWRfc2NvcmUYAiABKAUSFwoPY3B1X3Nx",
            "dWFkX3Njb3JlGAMgASgFEhQKDGlzX2dhbWVfb3ZlchgEIAEoCBIsCgl1c2Vy",
            "X2hhbmQYBSADKAsyGS5TY29wb25lX1NjaWVudGlmaWNvLmNhcmQSMgoObmV4",
            "dF9wbGF5ZXJfSUQYBiABKA4yGi5TY29wb25lX1NjaWVudGlmaWNvLkFjdG9y",
            "KjUKBFN1aXQSCgoGREVOQVJJEAASCQoFQ09QUEUQARILCgdCQVNUT05JEAIS",
            "CQoFU1BBREUQAyp8CgRSYW5rEgsKB1VOS05PV04QABIICgRBU1NPEAESBwoD",
            "RFVFEAISBwoDVFJFEAMSCwoHUVVBVFRSTxAEEgoKBkNJTlFVRRAFEgcKA1NF",
            "SRAGEgkKBVNFVFRFEAcSCQoFRkFOVEUQCBILCgdDQVZBTExPEAkSBgoCUkUQ",
            "Cio/CgVBY3RvchIICgRVU0VSEAASDQoJQ1BVX1JJR0hUEAESDwoLQ1BVX1BB",
            "UlRORVIQAhIMCghDUFVfTEVGVBADMusCCgpnb19iYWNrZW5kElQKCnN0YXJ0",
            "X2dhbWUSIi5TY29wb25lX1NjaWVudGlmaWNvLmdhbWVfc2V0dGluZ3MaIi5T",
            "Y29wb25lX1NjaWVudGlmaWNvLmluaXRpYWxfc3RhdGUSTwoJcGxheV9jYXJk",
            "EiAuU2NvcG9uZV9TY2llbnRpZmljby5QbGF5UmVxdWVzdBogLlNjb3BvbmVf",
            "U2NpZW50aWZpY28udHVybl91cGRhdGUSWAoMb2JzZXJ2ZV90dXJuEiQuU2Nv",
            "cG9uZV9TY2llbnRpZmljby5vYnNlcnZlX3JlcXVlc3QaIC5TY29wb25lX1Nj",
            "aWVudGlmaWNvLnR1cm5fdXBkYXRlMAESXAoRY2FsY29sYV9wdW50ZWdnaW8S",
            "JC5TY29wb25lX1NjaWVudGlmaWNvLm9ic2VydmVfcmVxdWVzdBohLlNjb3Bv",
            "bmVfU2NpZW50aWZpY28uc2NvcmVfdXBkYXRlQgZaBC4vcGJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ScoponeScientifico.Suit), typeof(global::ScoponeScientifico.Rank), typeof(global::ScoponeScientifico.Actor), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ScoponeScientifico.observe_request), global::ScoponeScientifico.observe_request.Parser, new[]{ "GameID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScoponeScientifico.game_settings), global::ScoponeScientifico.game_settings.Parser, new[]{ "UserName", "MaxPoints" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScoponeScientifico.card), global::ScoponeScientifico.card.Parser, new[]{ "Suit", "Rank" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScoponeScientifico.PlayRequest), global::ScoponeScientifico.PlayRequest.Parser, new[]{ "GameID", "PlayedCard", "TargetCard" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScoponeScientifico.Cobination), global::ScoponeScientifico.Cobination.Parser, new[]{ "Cards" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScoponeScientifico.initial_state), global::ScoponeScientifico.initial_state.Parser, new[]{ "GameID", "UserHand", "DealerID", "CurrentPlayer" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScoponeScientifico.turn_update), global::ScoponeScientifico.turn_update.Parser, new[]{ "Actor", "PlayedCard", "CartePrese", "Scopa", "IsMatchOver", "NextPlayerID", "ConflictResolutionNeeded", "Option" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScoponeScientifico.score_update), global::ScoponeScientifico.score_update.Parser, new[]{ "GameID", "UserSqudScore", "CpuSquadScore", "IsGameOver", "UserHand", "NextPlayerID" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Suit {
    [pbr::OriginalName("DENARI")] Denari = 0,
    [pbr::OriginalName("COPPE")] Coppe = 1,
    [pbr::OriginalName("BASTONI")] Bastoni = 2,
    [pbr::OriginalName("SPADE")] Spade = 3,
  }

  public enum Rank {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("ASSO")] Asso = 1,
    [pbr::OriginalName("DUE")] Due = 2,
    [pbr::OriginalName("TRE")] Tre = 3,
    [pbr::OriginalName("QUATTRO")] Quattro = 4,
    [pbr::OriginalName("CINQUE")] Cinque = 5,
    [pbr::OriginalName("SEI")] Sei = 6,
    [pbr::OriginalName("SETTE")] Sette = 7,
    [pbr::OriginalName("FANTE")] Fante = 8,
    [pbr::OriginalName("CAVALLO")] Cavallo = 9,
    [pbr::OriginalName("RE")] Re = 10,
  }

  public enum Actor {
    [pbr::OriginalName("USER")] User = 0,
    [pbr::OriginalName("CPU_RIGHT")] CpuRight = 1,
    [pbr::OriginalName("CPU_PARTNER")] CpuPartner = 2,
    [pbr::OriginalName("CPU_LEFT")] CpuLeft = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class observe_request : pb::IMessage<observe_request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<observe_request> _parser = new pb::MessageParser<observe_request>(() => new observe_request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<observe_request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScoponeScientifico.MessaggiPartitaReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public observe_request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public observe_request(observe_request other) : this() {
      gameID_ = other.gameID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public observe_request Clone() {
      return new observe_request(this);
    }

    /// <summary>Field number for the "game_ID" field.</summary>
    public const int GameIDFieldNumber = 1;
    private int gameID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GameID {
      get { return gameID_; }
      set {
        gameID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as observe_request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(observe_request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameID != other.GameID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameID != 0) hash ^= GameID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(observe_request other) {
      if (other == null) {
        return;
      }
      if (other.GameID != 0) {
        GameID = other.GameID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GameID = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GameID = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class game_settings : pb::IMessage<game_settings>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<game_settings> _parser = new pb::MessageParser<game_settings>(() => new game_settings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<game_settings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScoponeScientifico.MessaggiPartitaReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public game_settings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public game_settings(game_settings other) : this() {
      userName_ = other.userName_;
      maxPoints_ = other.maxPoints_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public game_settings Clone() {
      return new game_settings(this);
    }

    /// <summary>Field number for the "user_name" field.</summary>
    public const int UserNameFieldNumber = 1;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "max_points" field.</summary>
    public const int MaxPointsFieldNumber = 2;
    private int maxPoints_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxPoints {
      get { return maxPoints_; }
      set {
        maxPoints_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as game_settings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(game_settings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserName != other.UserName) return false;
      if (MaxPoints != other.MaxPoints) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserName.Length != 0) hash ^= UserName.GetHashCode();
      if (MaxPoints != 0) hash ^= MaxPoints.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserName);
      }
      if (MaxPoints != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MaxPoints);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserName);
      }
      if (MaxPoints != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MaxPoints);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (MaxPoints != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxPoints);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(game_settings other) {
      if (other == null) {
        return;
      }
      if (other.UserName.Length != 0) {
        UserName = other.UserName;
      }
      if (other.MaxPoints != 0) {
        MaxPoints = other.MaxPoints;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserName = input.ReadString();
            break;
          }
          case 16: {
            MaxPoints = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserName = input.ReadString();
            break;
          }
          case 16: {
            MaxPoints = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class card : pb::IMessage<card>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<card> _parser = new pb::MessageParser<card>(() => new card());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<card> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScoponeScientifico.MessaggiPartitaReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public card() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public card(card other) : this() {
      suit_ = other.suit_;
      rank_ = other.rank_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public card Clone() {
      return new card(this);
    }

    /// <summary>Field number for the "suit" field.</summary>
    public const int SuitFieldNumber = 2;
    private global::ScoponeScientifico.Suit suit_ = global::ScoponeScientifico.Suit.Denari;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ScoponeScientifico.Suit Suit {
      get { return suit_; }
      set {
        suit_ = value;
      }
    }

    /// <summary>Field number for the "rank" field.</summary>
    public const int RankFieldNumber = 3;
    private global::ScoponeScientifico.Rank rank_ = global::ScoponeScientifico.Rank.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ScoponeScientifico.Rank Rank {
      get { return rank_; }
      set {
        rank_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as card);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(card other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Suit != other.Suit) return false;
      if (Rank != other.Rank) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Suit != global::ScoponeScientifico.Suit.Denari) hash ^= Suit.GetHashCode();
      if (Rank != global::ScoponeScientifico.Rank.Unknown) hash ^= Rank.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Suit != global::ScoponeScientifico.Suit.Denari) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Suit);
      }
      if (Rank != global::ScoponeScientifico.Rank.Unknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Rank);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Suit != global::ScoponeScientifico.Suit.Denari) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Suit);
      }
      if (Rank != global::ScoponeScientifico.Rank.Unknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Rank);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Suit != global::ScoponeScientifico.Suit.Denari) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Suit);
      }
      if (Rank != global::ScoponeScientifico.Rank.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Rank);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(card other) {
      if (other == null) {
        return;
      }
      if (other.Suit != global::ScoponeScientifico.Suit.Denari) {
        Suit = other.Suit;
      }
      if (other.Rank != global::ScoponeScientifico.Rank.Unknown) {
        Rank = other.Rank;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            Suit = (global::ScoponeScientifico.Suit) input.ReadEnum();
            break;
          }
          case 24: {
            Rank = (global::ScoponeScientifico.Rank) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            Suit = (global::ScoponeScientifico.Suit) input.ReadEnum();
            break;
          }
          case 24: {
            Rank = (global::ScoponeScientifico.Rank) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayRequest : pb::IMessage<PlayRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayRequest> _parser = new pb::MessageParser<PlayRequest>(() => new PlayRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScoponeScientifico.MessaggiPartitaReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayRequest(PlayRequest other) : this() {
      gameID_ = other.gameID_;
      playedCard_ = other.playedCard_ != null ? other.playedCard_.Clone() : null;
      targetCard_ = other.targetCard_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayRequest Clone() {
      return new PlayRequest(this);
    }

    /// <summary>Field number for the "game_ID" field.</summary>
    public const int GameIDFieldNumber = 1;
    private int gameID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GameID {
      get { return gameID_; }
      set {
        gameID_ = value;
      }
    }

    /// <summary>Field number for the "played_card" field.</summary>
    public const int PlayedCardFieldNumber = 2;
    private global::ScoponeScientifico.card playedCard_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ScoponeScientifico.card PlayedCard {
      get { return playedCard_; }
      set {
        playedCard_ = value;
      }
    }

    /// <summary>Field number for the "target_card" field.</summary>
    public const int TargetCardFieldNumber = 3;
    private static readonly pb::FieldCodec<global::ScoponeScientifico.card> _repeated_targetCard_codec
        = pb::FieldCodec.ForMessage(26, global::ScoponeScientifico.card.Parser);
    private readonly pbc::RepeatedField<global::ScoponeScientifico.card> targetCard_ = new pbc::RepeatedField<global::ScoponeScientifico.card>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ScoponeScientifico.card> TargetCard {
      get { return targetCard_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameID != other.GameID) return false;
      if (!object.Equals(PlayedCard, other.PlayedCard)) return false;
      if(!targetCard_.Equals(other.targetCard_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameID != 0) hash ^= GameID.GetHashCode();
      if (playedCard_ != null) hash ^= PlayedCard.GetHashCode();
      hash ^= targetCard_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameID);
      }
      if (playedCard_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayedCard);
      }
      targetCard_.WriteTo(output, _repeated_targetCard_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameID);
      }
      if (playedCard_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayedCard);
      }
      targetCard_.WriteTo(ref output, _repeated_targetCard_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameID);
      }
      if (playedCard_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayedCard);
      }
      size += targetCard_.CalculateSize(_repeated_targetCard_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayRequest other) {
      if (other == null) {
        return;
      }
      if (other.GameID != 0) {
        GameID = other.GameID;
      }
      if (other.playedCard_ != null) {
        if (playedCard_ == null) {
          PlayedCard = new global::ScoponeScientifico.card();
        }
        PlayedCard.MergeFrom(other.PlayedCard);
      }
      targetCard_.Add(other.targetCard_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GameID = input.ReadInt32();
            break;
          }
          case 18: {
            if (playedCard_ == null) {
              PlayedCard = new global::ScoponeScientifico.card();
            }
            input.ReadMessage(PlayedCard);
            break;
          }
          case 26: {
            targetCard_.AddEntriesFrom(input, _repeated_targetCard_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GameID = input.ReadInt32();
            break;
          }
          case 18: {
            if (playedCard_ == null) {
              PlayedCard = new global::ScoponeScientifico.card();
            }
            input.ReadMessage(PlayedCard);
            break;
          }
          case 26: {
            targetCard_.AddEntriesFrom(ref input, _repeated_targetCard_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Cobination : pb::IMessage<Cobination>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Cobination> _parser = new pb::MessageParser<Cobination>(() => new Cobination());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Cobination> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScoponeScientifico.MessaggiPartitaReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cobination() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cobination(Cobination other) : this() {
      cards_ = other.cards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cobination Clone() {
      return new Cobination(this);
    }

    /// <summary>Field number for the "cards" field.</summary>
    public const int CardsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ScoponeScientifico.card> _repeated_cards_codec
        = pb::FieldCodec.ForMessage(10, global::ScoponeScientifico.card.Parser);
    private readonly pbc::RepeatedField<global::ScoponeScientifico.card> cards_ = new pbc::RepeatedField<global::ScoponeScientifico.card>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ScoponeScientifico.card> Cards {
      get { return cards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Cobination);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Cobination other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!cards_.Equals(other.cards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= cards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      cards_.WriteTo(output, _repeated_cards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      cards_.WriteTo(ref output, _repeated_cards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += cards_.CalculateSize(_repeated_cards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Cobination other) {
      if (other == null) {
        return;
      }
      cards_.Add(other.cards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            cards_.AddEntriesFrom(input, _repeated_cards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            cards_.AddEntriesFrom(ref input, _repeated_cards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class initial_state : pb::IMessage<initial_state>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<initial_state> _parser = new pb::MessageParser<initial_state>(() => new initial_state());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<initial_state> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScoponeScientifico.MessaggiPartitaReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public initial_state() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public initial_state(initial_state other) : this() {
      gameID_ = other.gameID_;
      userHand_ = other.userHand_.Clone();
      dealerID_ = other.dealerID_;
      currentPlayer_ = other.currentPlayer_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public initial_state Clone() {
      return new initial_state(this);
    }

    /// <summary>Field number for the "game_ID" field.</summary>
    public const int GameIDFieldNumber = 1;
    private int gameID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GameID {
      get { return gameID_; }
      set {
        gameID_ = value;
      }
    }

    /// <summary>Field number for the "user_hand" field.</summary>
    public const int UserHandFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ScoponeScientifico.card> _repeated_userHand_codec
        = pb::FieldCodec.ForMessage(18, global::ScoponeScientifico.card.Parser);
    private readonly pbc::RepeatedField<global::ScoponeScientifico.card> userHand_ = new pbc::RepeatedField<global::ScoponeScientifico.card>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ScoponeScientifico.card> UserHand {
      get { return userHand_; }
    }

    /// <summary>Field number for the "dealer_ID" field.</summary>
    public const int DealerIDFieldNumber = 3;
    private global::ScoponeScientifico.Actor dealerID_ = global::ScoponeScientifico.Actor.User;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ScoponeScientifico.Actor DealerID {
      get { return dealerID_; }
      set {
        dealerID_ = value;
      }
    }

    /// <summary>Field number for the "current_player" field.</summary>
    public const int CurrentPlayerFieldNumber = 4;
    private global::ScoponeScientifico.Actor currentPlayer_ = global::ScoponeScientifico.Actor.User;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ScoponeScientifico.Actor CurrentPlayer {
      get { return currentPlayer_; }
      set {
        currentPlayer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as initial_state);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(initial_state other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameID != other.GameID) return false;
      if(!userHand_.Equals(other.userHand_)) return false;
      if (DealerID != other.DealerID) return false;
      if (CurrentPlayer != other.CurrentPlayer) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameID != 0) hash ^= GameID.GetHashCode();
      hash ^= userHand_.GetHashCode();
      if (DealerID != global::ScoponeScientifico.Actor.User) hash ^= DealerID.GetHashCode();
      if (CurrentPlayer != global::ScoponeScientifico.Actor.User) hash ^= CurrentPlayer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameID);
      }
      userHand_.WriteTo(output, _repeated_userHand_codec);
      if (DealerID != global::ScoponeScientifico.Actor.User) {
        output.WriteRawTag(24);
        output.WriteEnum((int) DealerID);
      }
      if (CurrentPlayer != global::ScoponeScientifico.Actor.User) {
        output.WriteRawTag(32);
        output.WriteEnum((int) CurrentPlayer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameID);
      }
      userHand_.WriteTo(ref output, _repeated_userHand_codec);
      if (DealerID != global::ScoponeScientifico.Actor.User) {
        output.WriteRawTag(24);
        output.WriteEnum((int) DealerID);
      }
      if (CurrentPlayer != global::ScoponeScientifico.Actor.User) {
        output.WriteRawTag(32);
        output.WriteEnum((int) CurrentPlayer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameID);
      }
      size += userHand_.CalculateSize(_repeated_userHand_codec);
      if (DealerID != global::ScoponeScientifico.Actor.User) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DealerID);
      }
      if (CurrentPlayer != global::ScoponeScientifico.Actor.User) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CurrentPlayer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(initial_state other) {
      if (other == null) {
        return;
      }
      if (other.GameID != 0) {
        GameID = other.GameID;
      }
      userHand_.Add(other.userHand_);
      if (other.DealerID != global::ScoponeScientifico.Actor.User) {
        DealerID = other.DealerID;
      }
      if (other.CurrentPlayer != global::ScoponeScientifico.Actor.User) {
        CurrentPlayer = other.CurrentPlayer;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GameID = input.ReadInt32();
            break;
          }
          case 18: {
            userHand_.AddEntriesFrom(input, _repeated_userHand_codec);
            break;
          }
          case 24: {
            DealerID = (global::ScoponeScientifico.Actor) input.ReadEnum();
            break;
          }
          case 32: {
            CurrentPlayer = (global::ScoponeScientifico.Actor) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GameID = input.ReadInt32();
            break;
          }
          case 18: {
            userHand_.AddEntriesFrom(ref input, _repeated_userHand_codec);
            break;
          }
          case 24: {
            DealerID = (global::ScoponeScientifico.Actor) input.ReadEnum();
            break;
          }
          case 32: {
            CurrentPlayer = (global::ScoponeScientifico.Actor) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class turn_update : pb::IMessage<turn_update>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<turn_update> _parser = new pb::MessageParser<turn_update>(() => new turn_update());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<turn_update> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScoponeScientifico.MessaggiPartitaReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public turn_update() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public turn_update(turn_update other) : this() {
      actor_ = other.actor_;
      playedCard_ = other.playedCard_ != null ? other.playedCard_.Clone() : null;
      cartePrese_ = other.cartePrese_.Clone();
      scopa_ = other.scopa_;
      isMatchOver_ = other.isMatchOver_;
      nextPlayerID_ = other.nextPlayerID_;
      conflictResolutionNeeded_ = other.conflictResolutionNeeded_;
      option_ = other.option_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public turn_update Clone() {
      return new turn_update(this);
    }

    /// <summary>Field number for the "actor" field.</summary>
    public const int ActorFieldNumber = 1;
    private global::ScoponeScientifico.Actor actor_ = global::ScoponeScientifico.Actor.User;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ScoponeScientifico.Actor Actor {
      get { return actor_; }
      set {
        actor_ = value;
      }
    }

    /// <summary>Field number for the "played_card" field.</summary>
    public const int PlayedCardFieldNumber = 2;
    private global::ScoponeScientifico.card playedCard_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ScoponeScientifico.card PlayedCard {
      get { return playedCard_; }
      set {
        playedCard_ = value;
      }
    }

    /// <summary>Field number for the "carte_prese" field.</summary>
    public const int CartePreseFieldNumber = 3;
    private static readonly pb::FieldCodec<global::ScoponeScientifico.card> _repeated_cartePrese_codec
        = pb::FieldCodec.ForMessage(26, global::ScoponeScientifico.card.Parser);
    private readonly pbc::RepeatedField<global::ScoponeScientifico.card> cartePrese_ = new pbc::RepeatedField<global::ScoponeScientifico.card>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ScoponeScientifico.card> CartePrese {
      get { return cartePrese_; }
    }

    /// <summary>Field number for the "scopa" field.</summary>
    public const int ScopaFieldNumber = 4;
    private bool scopa_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Scopa {
      get { return scopa_; }
      set {
        scopa_ = value;
      }
    }

    /// <summary>Field number for the "is_match_over" field.</summary>
    public const int IsMatchOverFieldNumber = 5;
    private bool isMatchOver_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsMatchOver {
      get { return isMatchOver_; }
      set {
        isMatchOver_ = value;
      }
    }

    /// <summary>Field number for the "next_player_ID" field.</summary>
    public const int NextPlayerIDFieldNumber = 6;
    private global::ScoponeScientifico.Actor nextPlayerID_ = global::ScoponeScientifico.Actor.User;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ScoponeScientifico.Actor NextPlayerID {
      get { return nextPlayerID_; }
      set {
        nextPlayerID_ = value;
      }
    }

    /// <summary>Field number for the "conflict_resolution_needed" field.</summary>
    public const int ConflictResolutionNeededFieldNumber = 7;
    private bool conflictResolutionNeeded_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ConflictResolutionNeeded {
      get { return conflictResolutionNeeded_; }
      set {
        conflictResolutionNeeded_ = value;
      }
    }

    /// <summary>Field number for the "option" field.</summary>
    public const int OptionFieldNumber = 8;
    private static readonly pb::FieldCodec<global::ScoponeScientifico.Cobination> _repeated_option_codec
        = pb::FieldCodec.ForMessage(66, global::ScoponeScientifico.Cobination.Parser);
    private readonly pbc::RepeatedField<global::ScoponeScientifico.Cobination> option_ = new pbc::RepeatedField<global::ScoponeScientifico.Cobination>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ScoponeScientifico.Cobination> Option {
      get { return option_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as turn_update);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(turn_update other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Actor != other.Actor) return false;
      if (!object.Equals(PlayedCard, other.PlayedCard)) return false;
      if(!cartePrese_.Equals(other.cartePrese_)) return false;
      if (Scopa != other.Scopa) return false;
      if (IsMatchOver != other.IsMatchOver) return false;
      if (NextPlayerID != other.NextPlayerID) return false;
      if (ConflictResolutionNeeded != other.ConflictResolutionNeeded) return false;
      if(!option_.Equals(other.option_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Actor != global::ScoponeScientifico.Actor.User) hash ^= Actor.GetHashCode();
      if (playedCard_ != null) hash ^= PlayedCard.GetHashCode();
      hash ^= cartePrese_.GetHashCode();
      if (Scopa != false) hash ^= Scopa.GetHashCode();
      if (IsMatchOver != false) hash ^= IsMatchOver.GetHashCode();
      if (NextPlayerID != global::ScoponeScientifico.Actor.User) hash ^= NextPlayerID.GetHashCode();
      if (ConflictResolutionNeeded != false) hash ^= ConflictResolutionNeeded.GetHashCode();
      hash ^= option_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Actor != global::ScoponeScientifico.Actor.User) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Actor);
      }
      if (playedCard_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayedCard);
      }
      cartePrese_.WriteTo(output, _repeated_cartePrese_codec);
      if (Scopa != false) {
        output.WriteRawTag(32);
        output.WriteBool(Scopa);
      }
      if (IsMatchOver != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsMatchOver);
      }
      if (NextPlayerID != global::ScoponeScientifico.Actor.User) {
        output.WriteRawTag(48);
        output.WriteEnum((int) NextPlayerID);
      }
      if (ConflictResolutionNeeded != false) {
        output.WriteRawTag(56);
        output.WriteBool(ConflictResolutionNeeded);
      }
      option_.WriteTo(output, _repeated_option_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Actor != global::ScoponeScientifico.Actor.User) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Actor);
      }
      if (playedCard_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayedCard);
      }
      cartePrese_.WriteTo(ref output, _repeated_cartePrese_codec);
      if (Scopa != false) {
        output.WriteRawTag(32);
        output.WriteBool(Scopa);
      }
      if (IsMatchOver != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsMatchOver);
      }
      if (NextPlayerID != global::ScoponeScientifico.Actor.User) {
        output.WriteRawTag(48);
        output.WriteEnum((int) NextPlayerID);
      }
      if (ConflictResolutionNeeded != false) {
        output.WriteRawTag(56);
        output.WriteBool(ConflictResolutionNeeded);
      }
      option_.WriteTo(ref output, _repeated_option_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Actor != global::ScoponeScientifico.Actor.User) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Actor);
      }
      if (playedCard_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayedCard);
      }
      size += cartePrese_.CalculateSize(_repeated_cartePrese_codec);
      if (Scopa != false) {
        size += 1 + 1;
      }
      if (IsMatchOver != false) {
        size += 1 + 1;
      }
      if (NextPlayerID != global::ScoponeScientifico.Actor.User) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) NextPlayerID);
      }
      if (ConflictResolutionNeeded != false) {
        size += 1 + 1;
      }
      size += option_.CalculateSize(_repeated_option_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(turn_update other) {
      if (other == null) {
        return;
      }
      if (other.Actor != global::ScoponeScientifico.Actor.User) {
        Actor = other.Actor;
      }
      if (other.playedCard_ != null) {
        if (playedCard_ == null) {
          PlayedCard = new global::ScoponeScientifico.card();
        }
        PlayedCard.MergeFrom(other.PlayedCard);
      }
      cartePrese_.Add(other.cartePrese_);
      if (other.Scopa != false) {
        Scopa = other.Scopa;
      }
      if (other.IsMatchOver != false) {
        IsMatchOver = other.IsMatchOver;
      }
      if (other.NextPlayerID != global::ScoponeScientifico.Actor.User) {
        NextPlayerID = other.NextPlayerID;
      }
      if (other.ConflictResolutionNeeded != false) {
        ConflictResolutionNeeded = other.ConflictResolutionNeeded;
      }
      option_.Add(other.option_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Actor = (global::ScoponeScientifico.Actor) input.ReadEnum();
            break;
          }
          case 18: {
            if (playedCard_ == null) {
              PlayedCard = new global::ScoponeScientifico.card();
            }
            input.ReadMessage(PlayedCard);
            break;
          }
          case 26: {
            cartePrese_.AddEntriesFrom(input, _repeated_cartePrese_codec);
            break;
          }
          case 32: {
            Scopa = input.ReadBool();
            break;
          }
          case 40: {
            IsMatchOver = input.ReadBool();
            break;
          }
          case 48: {
            NextPlayerID = (global::ScoponeScientifico.Actor) input.ReadEnum();
            break;
          }
          case 56: {
            ConflictResolutionNeeded = input.ReadBool();
            break;
          }
          case 66: {
            option_.AddEntriesFrom(input, _repeated_option_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Actor = (global::ScoponeScientifico.Actor) input.ReadEnum();
            break;
          }
          case 18: {
            if (playedCard_ == null) {
              PlayedCard = new global::ScoponeScientifico.card();
            }
            input.ReadMessage(PlayedCard);
            break;
          }
          case 26: {
            cartePrese_.AddEntriesFrom(ref input, _repeated_cartePrese_codec);
            break;
          }
          case 32: {
            Scopa = input.ReadBool();
            break;
          }
          case 40: {
            IsMatchOver = input.ReadBool();
            break;
          }
          case 48: {
            NextPlayerID = (global::ScoponeScientifico.Actor) input.ReadEnum();
            break;
          }
          case 56: {
            ConflictResolutionNeeded = input.ReadBool();
            break;
          }
          case 66: {
            option_.AddEntriesFrom(ref input, _repeated_option_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class score_update : pb::IMessage<score_update>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<score_update> _parser = new pb::MessageParser<score_update>(() => new score_update());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<score_update> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScoponeScientifico.MessaggiPartitaReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public score_update() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public score_update(score_update other) : this() {
      gameID_ = other.gameID_;
      userSqudScore_ = other.userSqudScore_;
      cpuSquadScore_ = other.cpuSquadScore_;
      isGameOver_ = other.isGameOver_;
      userHand_ = other.userHand_.Clone();
      nextPlayerID_ = other.nextPlayerID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public score_update Clone() {
      return new score_update(this);
    }

    /// <summary>Field number for the "game_ID" field.</summary>
    public const int GameIDFieldNumber = 1;
    private int gameID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GameID {
      get { return gameID_; }
      set {
        gameID_ = value;
      }
    }

    /// <summary>Field number for the "user_squd_score" field.</summary>
    public const int UserSqudScoreFieldNumber = 2;
    private int userSqudScore_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UserSqudScore {
      get { return userSqudScore_; }
      set {
        userSqudScore_ = value;
      }
    }

    /// <summary>Field number for the "cpu_squad_score" field.</summary>
    public const int CpuSquadScoreFieldNumber = 3;
    private int cpuSquadScore_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CpuSquadScore {
      get { return cpuSquadScore_; }
      set {
        cpuSquadScore_ = value;
      }
    }

    /// <summary>Field number for the "is_game_over" field.</summary>
    public const int IsGameOverFieldNumber = 4;
    private bool isGameOver_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsGameOver {
      get { return isGameOver_; }
      set {
        isGameOver_ = value;
      }
    }

    /// <summary>Field number for the "user_hand" field.</summary>
    public const int UserHandFieldNumber = 5;
    private static readonly pb::FieldCodec<global::ScoponeScientifico.card> _repeated_userHand_codec
        = pb::FieldCodec.ForMessage(42, global::ScoponeScientifico.card.Parser);
    private readonly pbc::RepeatedField<global::ScoponeScientifico.card> userHand_ = new pbc::RepeatedField<global::ScoponeScientifico.card>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ScoponeScientifico.card> UserHand {
      get { return userHand_; }
    }

    /// <summary>Field number for the "next_player_ID" field.</summary>
    public const int NextPlayerIDFieldNumber = 6;
    private global::ScoponeScientifico.Actor nextPlayerID_ = global::ScoponeScientifico.Actor.User;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ScoponeScientifico.Actor NextPlayerID {
      get { return nextPlayerID_; }
      set {
        nextPlayerID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as score_update);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(score_update other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameID != other.GameID) return false;
      if (UserSqudScore != other.UserSqudScore) return false;
      if (CpuSquadScore != other.CpuSquadScore) return false;
      if (IsGameOver != other.IsGameOver) return false;
      if(!userHand_.Equals(other.userHand_)) return false;
      if (NextPlayerID != other.NextPlayerID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameID != 0) hash ^= GameID.GetHashCode();
      if (UserSqudScore != 0) hash ^= UserSqudScore.GetHashCode();
      if (CpuSquadScore != 0) hash ^= CpuSquadScore.GetHashCode();
      if (IsGameOver != false) hash ^= IsGameOver.GetHashCode();
      hash ^= userHand_.GetHashCode();
      if (NextPlayerID != global::ScoponeScientifico.Actor.User) hash ^= NextPlayerID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameID);
      }
      if (UserSqudScore != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UserSqudScore);
      }
      if (CpuSquadScore != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CpuSquadScore);
      }
      if (IsGameOver != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsGameOver);
      }
      userHand_.WriteTo(output, _repeated_userHand_codec);
      if (NextPlayerID != global::ScoponeScientifico.Actor.User) {
        output.WriteRawTag(48);
        output.WriteEnum((int) NextPlayerID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameID);
      }
      if (UserSqudScore != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UserSqudScore);
      }
      if (CpuSquadScore != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CpuSquadScore);
      }
      if (IsGameOver != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsGameOver);
      }
      userHand_.WriteTo(ref output, _repeated_userHand_codec);
      if (NextPlayerID != global::ScoponeScientifico.Actor.User) {
        output.WriteRawTag(48);
        output.WriteEnum((int) NextPlayerID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameID);
      }
      if (UserSqudScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserSqudScore);
      }
      if (CpuSquadScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CpuSquadScore);
      }
      if (IsGameOver != false) {
        size += 1 + 1;
      }
      size += userHand_.CalculateSize(_repeated_userHand_codec);
      if (NextPlayerID != global::ScoponeScientifico.Actor.User) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) NextPlayerID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(score_update other) {
      if (other == null) {
        return;
      }
      if (other.GameID != 0) {
        GameID = other.GameID;
      }
      if (other.UserSqudScore != 0) {
        UserSqudScore = other.UserSqudScore;
      }
      if (other.CpuSquadScore != 0) {
        CpuSquadScore = other.CpuSquadScore;
      }
      if (other.IsGameOver != false) {
        IsGameOver = other.IsGameOver;
      }
      userHand_.Add(other.userHand_);
      if (other.NextPlayerID != global::ScoponeScientifico.Actor.User) {
        NextPlayerID = other.NextPlayerID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GameID = input.ReadInt32();
            break;
          }
          case 16: {
            UserSqudScore = input.ReadInt32();
            break;
          }
          case 24: {
            CpuSquadScore = input.ReadInt32();
            break;
          }
          case 32: {
            IsGameOver = input.ReadBool();
            break;
          }
          case 42: {
            userHand_.AddEntriesFrom(input, _repeated_userHand_codec);
            break;
          }
          case 48: {
            NextPlayerID = (global::ScoponeScientifico.Actor) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GameID = input.ReadInt32();
            break;
          }
          case 16: {
            UserSqudScore = input.ReadInt32();
            break;
          }
          case 24: {
            CpuSquadScore = input.ReadInt32();
            break;
          }
          case 32: {
            IsGameOver = input.ReadBool();
            break;
          }
          case 42: {
            userHand_.AddEntriesFrom(ref input, _repeated_userHand_codec);
            break;
          }
          case 48: {
            NextPlayerID = (global::ScoponeScientifico.Actor) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
