syntax= "proto3";

package Scopone_Scientifico;

option go_package = "./pb";

enum Suit {
    DENARI = 0;
    COPPE = 1;
    BASTONI = 2;
    SPADE = 3;
}

enum Rank {
    UNKNOWN = 0; 
    ASSO = 1;
    DUE = 2;
    TRE = 3;
    QUATTRO = 4;
    CINQUE = 5;
    SEI = 6;
    SETTE = 7;
    FANTE = 8;
    CAVALLO = 9;
    RE = 10;
}

enum Actor {
    USER = 0;        
    CPU_RIGHT = 1;   
    CPU_PARTNER = 2; 
    CPU_LEFT = 3; 
}   

message observe_request{
    int32 game_ID = 1;
}

message game_settings {
    string user_name = 1;
    int32 max_points = 2;
}

message card{
    int32 game_ID = 1;
    Suit  suit = 2;
    Rank  rank = 3;
}

message initial_state{
    int32 game_ID = 1;
    repeated card user_hand = 2;
    Actor dealer_ID = 3;
    Actor current_player = 4;
}

message turn_update{
    Actor actor = 1;
    card played_card = 2;
    repeated card carte_prese = 3;
    bool scopa = 4;
    bool is_match_over = 5;
    Actor next_player_ID = 6;
}

message score_update{
    int32 game_ID = 1;
    int32 user_squd_score = 2;
    int32 cpu_squad_score = 3;
    bool is_game_over = 4;
    repeated card user_hand = 5;
    Actor next_player_ID = 6;
}


service go_backend{
    rpc start_game (game_settings) returns (initial_state);
    rpc play_card  (card) returns (stream turn_update);
    rpc observe_turn (observe_request) returns (stream turn_update);
    rpc calcola_punteggio (observe_request) returns (score_update);
}
