// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: messaggi_partita.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoBackend_StartGame_FullMethodName        = "/Scopone_Scientifico.go_backend/start_game"
	GoBackend_PlayCard_FullMethodName         = "/Scopone_Scientifico.go_backend/play_card"
	GoBackend_ObserveTurn_FullMethodName      = "/Scopone_Scientifico.go_backend/observe_turn"
	GoBackend_CalcolaPunteggio_FullMethodName = "/Scopone_Scientifico.go_backend/calcola_punteggio"
)

// GoBackendClient is the client API for GoBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoBackendClient interface {
	StartGame(ctx context.Context, in *GameSettings, opts ...grpc.CallOption) (*InitialState, error)
	PlayCard(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*TurnUpdate, error)
	ObserveTurn(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TurnUpdate], error)
	CalcolaPunteggio(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ScoreUpdate, error)
}

type goBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewGoBackendClient(cc grpc.ClientConnInterface) GoBackendClient {
	return &goBackendClient{cc}
}

func (c *goBackendClient) StartGame(ctx context.Context, in *GameSettings, opts ...grpc.CallOption) (*InitialState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitialState)
	err := c.cc.Invoke(ctx, GoBackend_StartGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goBackendClient) PlayCard(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*TurnUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurnUpdate)
	err := c.cc.Invoke(ctx, GoBackend_PlayCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goBackendClient) ObserveTurn(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TurnUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoBackend_ServiceDesc.Streams[0], GoBackend_ObserveTurn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ObserveRequest, TurnUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoBackend_ObserveTurnClient = grpc.ServerStreamingClient[TurnUpdate]

func (c *goBackendClient) CalcolaPunteggio(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ScoreUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreUpdate)
	err := c.cc.Invoke(ctx, GoBackend_CalcolaPunteggio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoBackendServer is the server API for GoBackend service.
// All implementations must embed UnimplementedGoBackendServer
// for forward compatibility.
type GoBackendServer interface {
	StartGame(context.Context, *GameSettings) (*InitialState, error)
	PlayCard(context.Context, *PlayRequest) (*TurnUpdate, error)
	ObserveTurn(*ObserveRequest, grpc.ServerStreamingServer[TurnUpdate]) error
	CalcolaPunteggio(context.Context, *ObserveRequest) (*ScoreUpdate, error)
	mustEmbedUnimplementedGoBackendServer()
}

// UnimplementedGoBackendServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoBackendServer struct{}

func (UnimplementedGoBackendServer) StartGame(context.Context, *GameSettings) (*InitialState, error) {
	return nil, status.Error(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedGoBackendServer) PlayCard(context.Context, *PlayRequest) (*TurnUpdate, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayCard not implemented")
}
func (UnimplementedGoBackendServer) ObserveTurn(*ObserveRequest, grpc.ServerStreamingServer[TurnUpdate]) error {
	return status.Error(codes.Unimplemented, "method ObserveTurn not implemented")
}
func (UnimplementedGoBackendServer) CalcolaPunteggio(context.Context, *ObserveRequest) (*ScoreUpdate, error) {
	return nil, status.Error(codes.Unimplemented, "method CalcolaPunteggio not implemented")
}
func (UnimplementedGoBackendServer) mustEmbedUnimplementedGoBackendServer() {}
func (UnimplementedGoBackendServer) testEmbeddedByValue()                   {}

// UnsafeGoBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoBackendServer will
// result in compilation errors.
type UnsafeGoBackendServer interface {
	mustEmbedUnimplementedGoBackendServer()
}

func RegisterGoBackendServer(s grpc.ServiceRegistrar, srv GoBackendServer) {
	// If the following call panics, it indicates UnimplementedGoBackendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoBackend_ServiceDesc, srv)
}

func _GoBackend_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBackendServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoBackend_StartGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBackendServer).StartGame(ctx, req.(*GameSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoBackend_PlayCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBackendServer).PlayCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoBackend_PlayCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBackendServer).PlayCard(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoBackend_ObserveTurn_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObserveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoBackendServer).ObserveTurn(m, &grpc.GenericServerStream[ObserveRequest, TurnUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoBackend_ObserveTurnServer = grpc.ServerStreamingServer[TurnUpdate]

func _GoBackend_CalcolaPunteggio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBackendServer).CalcolaPunteggio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoBackend_CalcolaPunteggio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBackendServer).CalcolaPunteggio(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoBackend_ServiceDesc is the grpc.ServiceDesc for GoBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Scopone_Scientifico.go_backend",
	HandlerType: (*GoBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "start_game",
			Handler:    _GoBackend_StartGame_Handler,
		},
		{
			MethodName: "play_card",
			Handler:    _GoBackend_PlayCard_Handler,
		},
		{
			MethodName: "calcola_punteggio",
			Handler:    _GoBackend_CalcolaPunteggio_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "observe_turn",
			Handler:       _GoBackend_ObserveTurn_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "messaggi_partita.proto",
}
