// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: messaggi_partita.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Suit int32

const (
	Suit_DENARI  Suit = 0
	Suit_COPPE   Suit = 1
	Suit_BASTONI Suit = 2
	Suit_SPADE   Suit = 3
)

// Enum value maps for Suit.
var (
	Suit_name = map[int32]string{
		0: "DENARI",
		1: "COPPE",
		2: "BASTONI",
		3: "SPADE",
	}
	Suit_value = map[string]int32{
		"DENARI":  0,
		"COPPE":   1,
		"BASTONI": 2,
		"SPADE":   3,
	}
)

func (x Suit) Enum() *Suit {
	p := new(Suit)
	*p = x
	return p
}

func (x Suit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Suit) Descriptor() protoreflect.EnumDescriptor {
	return file_messaggi_partita_proto_enumTypes[0].Descriptor()
}

func (Suit) Type() protoreflect.EnumType {
	return &file_messaggi_partita_proto_enumTypes[0]
}

func (x Suit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Suit.Descriptor instead.
func (Suit) EnumDescriptor() ([]byte, []int) {
	return file_messaggi_partita_proto_rawDescGZIP(), []int{0}
}

type Rank int32

const (
	Rank_UNKNOWN Rank = 0
	Rank_ASSO    Rank = 1
	Rank_DUE     Rank = 2
	Rank_TRE     Rank = 3
	Rank_QUATTRO Rank = 4
	Rank_CINQUE  Rank = 5
	Rank_SEI     Rank = 6
	Rank_SETTE   Rank = 7
	Rank_FANTE   Rank = 8
	Rank_CAVALLO Rank = 9
	Rank_RE      Rank = 10
)

// Enum value maps for Rank.
var (
	Rank_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "ASSO",
		2:  "DUE",
		3:  "TRE",
		4:  "QUATTRO",
		5:  "CINQUE",
		6:  "SEI",
		7:  "SETTE",
		8:  "FANTE",
		9:  "CAVALLO",
		10: "RE",
	}
	Rank_value = map[string]int32{
		"UNKNOWN": 0,
		"ASSO":    1,
		"DUE":     2,
		"TRE":     3,
		"QUATTRO": 4,
		"CINQUE":  5,
		"SEI":     6,
		"SETTE":   7,
		"FANTE":   8,
		"CAVALLO": 9,
		"RE":      10,
	}
)

func (x Rank) Enum() *Rank {
	p := new(Rank)
	*p = x
	return p
}

func (x Rank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rank) Descriptor() protoreflect.EnumDescriptor {
	return file_messaggi_partita_proto_enumTypes[1].Descriptor()
}

func (Rank) Type() protoreflect.EnumType {
	return &file_messaggi_partita_proto_enumTypes[1]
}

func (x Rank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rank.Descriptor instead.
func (Rank) EnumDescriptor() ([]byte, []int) {
	return file_messaggi_partita_proto_rawDescGZIP(), []int{1}
}

type Actor int32

const (
	Actor_USER        Actor = 0
	Actor_CPU_RIGHT   Actor = 1
	Actor_CPU_PARTNER Actor = 2
	Actor_CPU_LEFT    Actor = 3
)

// Enum value maps for Actor.
var (
	Actor_name = map[int32]string{
		0: "USER",
		1: "CPU_RIGHT",
		2: "CPU_PARTNER",
		3: "CPU_LEFT",
	}
	Actor_value = map[string]int32{
		"USER":        0,
		"CPU_RIGHT":   1,
		"CPU_PARTNER": 2,
		"CPU_LEFT":    3,
	}
)

func (x Actor) Enum() *Actor {
	p := new(Actor)
	*p = x
	return p
}

func (x Actor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Actor) Descriptor() protoreflect.EnumDescriptor {
	return file_messaggi_partita_proto_enumTypes[2].Descriptor()
}

func (Actor) Type() protoreflect.EnumType {
	return &file_messaggi_partita_proto_enumTypes[2]
}

func (x Actor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Actor.Descriptor instead.
func (Actor) EnumDescriptor() ([]byte, []int) {
	return file_messaggi_partita_proto_rawDescGZIP(), []int{2}
}

type ObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game_ID       int32                  `protobuf:"varint,1,opt,name=game_ID,json=gameID,proto3" json:"game_ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_messaggi_partita_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messaggi_partita_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_messaggi_partita_proto_rawDescGZIP(), []int{0}
}

func (x *ObserveRequest) GetGame_ID() int32 {
	if x != nil {
		return x.Game_ID
	}
	return 0
}

type GameSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	MaxPoints     int32                  `protobuf:"varint,2,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSettings) Reset() {
	*x = GameSettings{}
	mi := &file_messaggi_partita_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSettings) ProtoMessage() {}

func (x *GameSettings) ProtoReflect() protoreflect.Message {
	mi := &file_messaggi_partita_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSettings.ProtoReflect.Descriptor instead.
func (*GameSettings) Descriptor() ([]byte, []int) {
	return file_messaggi_partita_proto_rawDescGZIP(), []int{1}
}

func (x *GameSettings) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GameSettings) GetMaxPoints() int32 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game_ID       int32                  `protobuf:"varint,1,opt,name=game_ID,json=gameID,proto3" json:"game_ID,omitempty"`
	Suit          Suit                   `protobuf:"varint,2,opt,name=suit,proto3,enum=Scopone_Scientifico.Suit" json:"suit,omitempty"`
	Rank          Rank                   `protobuf:"varint,3,opt,name=rank,proto3,enum=Scopone_Scientifico.Rank" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_messaggi_partita_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_messaggi_partita_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_messaggi_partita_proto_rawDescGZIP(), []int{2}
}

func (x *Card) GetGame_ID() int32 {
	if x != nil {
		return x.Game_ID
	}
	return 0
}

func (x *Card) GetSuit() Suit {
	if x != nil {
		return x.Suit
	}
	return Suit_DENARI
}

func (x *Card) GetRank() Rank {
	if x != nil {
		return x.Rank
	}
	return Rank_UNKNOWN
}

type InitialState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game_ID       int32                  `protobuf:"varint,1,opt,name=game_ID,json=gameID,proto3" json:"game_ID,omitempty"`
	UserHand      []*Card                `protobuf:"bytes,2,rep,name=user_hand,json=userHand,proto3" json:"user_hand,omitempty"`
	Dealer_ID     Actor                  `protobuf:"varint,3,opt,name=dealer_ID,json=dealerID,proto3,enum=Scopone_Scientifico.Actor" json:"dealer_ID,omitempty"`
	CurrentPlayer Actor                  `protobuf:"varint,4,opt,name=current_player,json=currentPlayer,proto3,enum=Scopone_Scientifico.Actor" json:"current_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialState) Reset() {
	*x = InitialState{}
	mi := &file_messaggi_partita_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialState) ProtoMessage() {}

func (x *InitialState) ProtoReflect() protoreflect.Message {
	mi := &file_messaggi_partita_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialState.ProtoReflect.Descriptor instead.
func (*InitialState) Descriptor() ([]byte, []int) {
	return file_messaggi_partita_proto_rawDescGZIP(), []int{3}
}

func (x *InitialState) GetGame_ID() int32 {
	if x != nil {
		return x.Game_ID
	}
	return 0
}

func (x *InitialState) GetUserHand() []*Card {
	if x != nil {
		return x.UserHand
	}
	return nil
}

func (x *InitialState) GetDealer_ID() Actor {
	if x != nil {
		return x.Dealer_ID
	}
	return Actor_USER
}

func (x *InitialState) GetCurrentPlayer() Actor {
	if x != nil {
		return x.CurrentPlayer
	}
	return Actor_USER
}

type TurnUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         Actor                  `protobuf:"varint,1,opt,name=actor,proto3,enum=Scopone_Scientifico.Actor" json:"actor,omitempty"`
	PlayedCard    *Card                  `protobuf:"bytes,2,opt,name=played_card,json=playedCard,proto3" json:"played_card,omitempty"`
	CartePrese    []*Card                `protobuf:"bytes,3,rep,name=carte_prese,json=cartePrese,proto3" json:"carte_prese,omitempty"`
	Scopa         bool                   `protobuf:"varint,4,opt,name=scopa,proto3" json:"scopa,omitempty"`
	IsMatchOver   bool                   `protobuf:"varint,5,opt,name=is_match_over,json=isMatchOver,proto3" json:"is_match_over,omitempty"`
	NextPlayer_ID Actor                  `protobuf:"varint,6,opt,name=next_player_ID,json=nextPlayerID,proto3,enum=Scopone_Scientifico.Actor" json:"next_player_ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnUpdate) Reset() {
	*x = TurnUpdate{}
	mi := &file_messaggi_partita_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnUpdate) ProtoMessage() {}

func (x *TurnUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messaggi_partita_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnUpdate.ProtoReflect.Descriptor instead.
func (*TurnUpdate) Descriptor() ([]byte, []int) {
	return file_messaggi_partita_proto_rawDescGZIP(), []int{4}
}

func (x *TurnUpdate) GetActor() Actor {
	if x != nil {
		return x.Actor
	}
	return Actor_USER
}

func (x *TurnUpdate) GetPlayedCard() *Card {
	if x != nil {
		return x.PlayedCard
	}
	return nil
}

func (x *TurnUpdate) GetCartePrese() []*Card {
	if x != nil {
		return x.CartePrese
	}
	return nil
}

func (x *TurnUpdate) GetScopa() bool {
	if x != nil {
		return x.Scopa
	}
	return false
}

func (x *TurnUpdate) GetIsMatchOver() bool {
	if x != nil {
		return x.IsMatchOver
	}
	return false
}

func (x *TurnUpdate) GetNextPlayer_ID() Actor {
	if x != nil {
		return x.NextPlayer_ID
	}
	return Actor_USER
}

var File_messaggi_partita_proto protoreflect.FileDescriptor

const file_messaggi_partita_proto_rawDesc = "" +
	"\n" +
	"\x16messaggi_partita.proto\x12\x13Scopone_Scientifico\"*\n" +
	"\x0fobserve_request\x12\x17\n" +
	"\agame_ID\x18\x01 \x01(\x05R\x06gameID\"K\n" +
	"\rgame_settings\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"max_points\x18\x02 \x01(\x05R\tmaxPoints\"}\n" +
	"\x04card\x12\x17\n" +
	"\agame_ID\x18\x01 \x01(\x05R\x06gameID\x12-\n" +
	"\x04suit\x18\x02 \x01(\x0e2\x19.Scopone_Scientifico.SuitR\x04suit\x12-\n" +
	"\x04rank\x18\x03 \x01(\x0e2\x19.Scopone_Scientifico.RankR\x04rank\"\xdc\x01\n" +
	"\rinitial_state\x12\x17\n" +
	"\agame_ID\x18\x01 \x01(\x05R\x06gameID\x126\n" +
	"\tuser_hand\x18\x02 \x03(\v2\x19.Scopone_Scientifico.cardR\buserHand\x127\n" +
	"\tdealer_ID\x18\x03 \x01(\x0e2\x1a.Scopone_Scientifico.ActorR\bdealerID\x12A\n" +
	"\x0ecurrent_player\x18\x04 \x01(\x0e2\x1a.Scopone_Scientifico.ActorR\rcurrentPlayer\"\xb3\x02\n" +
	"\vturn_update\x120\n" +
	"\x05actor\x18\x01 \x01(\x0e2\x1a.Scopone_Scientifico.ActorR\x05actor\x12:\n" +
	"\vplayed_card\x18\x02 \x01(\v2\x19.Scopone_Scientifico.cardR\n" +
	"playedCard\x12:\n" +
	"\vcarte_prese\x18\x03 \x03(\v2\x19.Scopone_Scientifico.cardR\n" +
	"cartePrese\x12\x14\n" +
	"\x05scopa\x18\x04 \x01(\bR\x05scopa\x12\"\n" +
	"\ris_match_over\x18\x05 \x01(\bR\visMatchOver\x12@\n" +
	"\x0enext_player_ID\x18\x06 \x01(\x0e2\x1a.Scopone_Scientifico.ActorR\fnextPlayerID*5\n" +
	"\x04Suit\x12\n" +
	"\n" +
	"\x06DENARI\x10\x00\x12\t\n" +
	"\x05COPPE\x10\x01\x12\v\n" +
	"\aBASTONI\x10\x02\x12\t\n" +
	"\x05SPADE\x10\x03*|\n" +
	"\x04Rank\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04ASSO\x10\x01\x12\a\n" +
	"\x03DUE\x10\x02\x12\a\n" +
	"\x03TRE\x10\x03\x12\v\n" +
	"\aQUATTRO\x10\x04\x12\n" +
	"\n" +
	"\x06CINQUE\x10\x05\x12\a\n" +
	"\x03SEI\x10\x06\x12\t\n" +
	"\x05SETTE\x10\a\x12\t\n" +
	"\x05FANTE\x10\b\x12\v\n" +
	"\aCAVALLO\x10\t\x12\x06\n" +
	"\x02RE\x10\n" +
	"*?\n" +
	"\x05Actor\x12\b\n" +
	"\x04USER\x10\x00\x12\r\n" +
	"\tCPU_RIGHT\x10\x01\x12\x0f\n" +
	"\vCPU_PARTNER\x10\x02\x12\f\n" +
	"\bCPU_LEFT\x10\x032\x88\x02\n" +
	"\n" +
	"go_backend\x12T\n" +
	"\n" +
	"start_game\x12\".Scopone_Scientifico.game_settings\x1a\".Scopone_Scientifico.initial_state\x12J\n" +
	"\tplay_card\x12\x19.Scopone_Scientifico.card\x1a .Scopone_Scientifico.turn_update0\x01\x12X\n" +
	"\fobserve_turn\x12$.Scopone_Scientifico.observe_request\x1a .Scopone_Scientifico.turn_update0\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_messaggi_partita_proto_rawDescOnce sync.Once
	file_messaggi_partita_proto_rawDescData []byte
)

func file_messaggi_partita_proto_rawDescGZIP() []byte {
	file_messaggi_partita_proto_rawDescOnce.Do(func() {
		file_messaggi_partita_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messaggi_partita_proto_rawDesc), len(file_messaggi_partita_proto_rawDesc)))
	})
	return file_messaggi_partita_proto_rawDescData
}

var file_messaggi_partita_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_messaggi_partita_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_messaggi_partita_proto_goTypes = []any{
	(Suit)(0),              // 0: Scopone_Scientifico.Suit
	(Rank)(0),              // 1: Scopone_Scientifico.Rank
	(Actor)(0),             // 2: Scopone_Scientifico.Actor
	(*ObserveRequest)(nil), // 3: Scopone_Scientifico.observe_request
	(*GameSettings)(nil),   // 4: Scopone_Scientifico.game_settings
	(*Card)(nil),           // 5: Scopone_Scientifico.card
	(*InitialState)(nil),   // 6: Scopone_Scientifico.initial_state
	(*TurnUpdate)(nil),     // 7: Scopone_Scientifico.turn_update
}
var file_messaggi_partita_proto_depIdxs = []int32{
	0,  // 0: Scopone_Scientifico.card.suit:type_name -> Scopone_Scientifico.Suit
	1,  // 1: Scopone_Scientifico.card.rank:type_name -> Scopone_Scientifico.Rank
	5,  // 2: Scopone_Scientifico.initial_state.user_hand:type_name -> Scopone_Scientifico.card
	2,  // 3: Scopone_Scientifico.initial_state.dealer_ID:type_name -> Scopone_Scientifico.Actor
	2,  // 4: Scopone_Scientifico.initial_state.current_player:type_name -> Scopone_Scientifico.Actor
	2,  // 5: Scopone_Scientifico.turn_update.actor:type_name -> Scopone_Scientifico.Actor
	5,  // 6: Scopone_Scientifico.turn_update.played_card:type_name -> Scopone_Scientifico.card
	5,  // 7: Scopone_Scientifico.turn_update.carte_prese:type_name -> Scopone_Scientifico.card
	2,  // 8: Scopone_Scientifico.turn_update.next_player_ID:type_name -> Scopone_Scientifico.Actor
	4,  // 9: Scopone_Scientifico.go_backend.start_game:input_type -> Scopone_Scientifico.game_settings
	5,  // 10: Scopone_Scientifico.go_backend.play_card:input_type -> Scopone_Scientifico.card
	3,  // 11: Scopone_Scientifico.go_backend.observe_turn:input_type -> Scopone_Scientifico.observe_request
	6,  // 12: Scopone_Scientifico.go_backend.start_game:output_type -> Scopone_Scientifico.initial_state
	7,  // 13: Scopone_Scientifico.go_backend.play_card:output_type -> Scopone_Scientifico.turn_update
	7,  // 14: Scopone_Scientifico.go_backend.observe_turn:output_type -> Scopone_Scientifico.turn_update
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_messaggi_partita_proto_init() }
func file_messaggi_partita_proto_init() {
	if File_messaggi_partita_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messaggi_partita_proto_rawDesc), len(file_messaggi_partita_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messaggi_partita_proto_goTypes,
		DependencyIndexes: file_messaggi_partita_proto_depIdxs,
		EnumInfos:         file_messaggi_partita_proto_enumTypes,
		MessageInfos:      file_messaggi_partita_proto_msgTypes,
	}.Build()
	File_messaggi_partita_proto = out.File
	file_messaggi_partita_proto_goTypes = nil
	file_messaggi_partita_proto_depIdxs = nil
}
